### ISSUE TITLE
CSV Import Plus

### ISSUE THREAD

**Issue by Daniel-KM** [omeka-s-modules/CSVImport#87]
Hi,

Thanks for this module.

I was wondering if it is preferable to push the improvements I made for the plugin Csv Import for Omeka (https://github.com/Daniel-KM/CsvImportPlus) here or if It is preferable to upgrade csv import plus separately.

Features I need are:

- [x] more parameters for the format of csv (tabulation, pipe, spaces, quotes, end of line, etc) (#91)
- [x] possibility to import item sets metadata (#99)
- [x] possibility to import media metadata (#102)
- [x] possibility to import various types of resource simultaneously (via a selectable identifier) (https://github.com/omeka-s-modules/CSVImport/pull/105/commits/7fd40c0ba799fbf96204801c5d6f5319c4607733)
- [x] possibility to bypass the mapping form (#101)
- [x] possibility to import from one folder on the file system (ok via FileSideload)
- [x] automatic check the whole csv before import (https://github.com/omeka-s-modules/CSVImport/pull/112/commits/fe6741b9a329eb2e5d4276ffe66812e978fc341d)
- [x] possibility to update or to delete the data (#94, #102)
- [x] save params as users settings (#96,  #97)
- [x] possibility to set the collection(s) of an item by name and not only by id (#103)
- [x] improved logs (https://github.com/omeka-s-modules/CSVImport/pull/105/commits/e5daedfa1765f2f1d9469821780ffceaab03c974)
- [x] improved tests (#104)
- [ ] possibility to automap multilingual values with headers like `dcterms:title:fre` or `Title : fre`
- [x] possibility to import directly [TSV](https://en.wikipedia.org/wiki/Tab-separated_values) (tab separated value) (https://github.com/omeka-s-modules/CSVImport/pull/105/commits/eef88daf30775dbada50cacff71f851ca44a3634) and [ODS](http://opendocumentformat.org/aboutODF) (OpenDocument Spreadsheet) (https://github.com/omeka-s-modules/CSVImport/pull/105/commits/e9c77cb71a10acd63cf3efd617e90ae2f14938c0)
- [x] improve the stop job

Other ones seem to have been included by default or may be implemented via new triggers (I'm adding one for the tags of [Folksonomy](https://github.com/Daniel-KM/Omeka-S-module-Folksonomy)).

Sincerely,

Daniel Berthereau
Digital Humanities, Infodoc & Knowledge management

**Comment by patrickmj** [comment]
I'd like to lean toward integrating such features into the existing CSV Import if possible. The user interfaces might get quite complicated, but if we can figure out a way to do it I think it'd be helpful. The redesign of CSV Import for Omeka S should also make it easier for other modules to add in some of the functionality you describe as separate, related pieces of code. Some examples of that are in my responses to your feature list:


-     more parameters for the format of csv (tabulation, pipe, spaces, quotes, end of line, etc);
-     possibility to import item sets and media metadata,

Importing item sets seems like a close analogy to the added ability to import User data. That could be directly added to the module, or with the possible addition of a new hook, maybe a module could add that separately.

Media metadata seems like it could/should go into a new tab on the mapping page. Again, this might call for a new event to trigger to add. I'd have to look in to that a bit. Alternatively, I could see this as a feature added by a separate module that does more fancy things, like the way Mapping adds features.

-     possibility to set the collection(s) of an item by name and not only by id,

My worry with this feature is that item set titles are not unique. Thus, it's quite possible to have an ambiguity problem.


-     possibility to import various types of resource simultaneously (via a selectable identifier),

This might be something from a new module, that gets put into the interface via a new button on the mapping page? The Mapping module adds a bunch of options that way.

-     possibility to bypass the mapping form,

This sounds like a configuration feature, one that creates the option to skip the mapping entirely and just run with the defaults. It's on the opposite side of the spectrum from the more complex features you talk about, but seems like a reasonable option to add directly to the module.

-     possibility to import from one folder on the file system,

The FileSideload module integrates with CSV Import, so this is already taken care of.

-     possibility to check the whole csv before import,

Could you tell more about what kind of checking you would like to do? I'm hesitant to move toward CSV validation and testing, as that should probably happen in the CSV creation.

-     possibility to update or to delete the data.

Imports can already be undone, which would delete the data. Updating based on some identifying data seems helpful, as you have done with Omeka Classic. Seems also like a reasonable new kind of import type, either directly in CSV Import or again as a separate module that slides in that functionality. (Also with the possible need to add an event).

**Comment by Daniel-KM** [comment]
To improve the logs, not only the number of items created, but the number of any resources, added, updated, replaced, or errors too, the column "added_count" should be changed to something like "data" or "stats", so it will be commited soon.

**Comment by Daniel-KM** [comment]
I'm adding the default headers as user params.

**Comment by Daniel-KM** [comment]
The last point of previous comment was done via user settings #101.

**Comment by Daniel-KM** [comment]
I'll integrate the last three points in some weeks.

**Comment by Daniel-KM** [comment]
Added import of resources (item sets, items and media) in bulk and improved logs in #105.
